// Regenerate with:
// PATH="/home/kit/.local/protoc/bin:/home/kit/go/bin:$PATH" \
// protoc --go_out=. --go_opt=paths=source_relative \
//   --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//   proto/a2a/a2a.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/a2a/a2a.proto

package a2a

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED  TaskState = 0
	TaskState_TASK_STATE_SUBMITTED    TaskState = 1
	TaskState_TASK_STATE_WORKING      TaskState = 2
	TaskState_TASK_STATE_COMPLETED    TaskState = 3
	TaskState_TASK_STATE_FAILED       TaskState = 4
	TaskState_TASK_STATE_CANCELED     TaskState = 5
	TaskState_TASK_STATE_INPUT_NEEDED TaskState = 6
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_SUBMITTED",
		2: "TASK_STATE_WORKING",
		3: "TASK_STATE_COMPLETED",
		4: "TASK_STATE_FAILED",
		5: "TASK_STATE_CANCELED",
		6: "TASK_STATE_INPUT_NEEDED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED":  0,
		"TASK_STATE_SUBMITTED":    1,
		"TASK_STATE_WORKING":      2,
		"TASK_STATE_COMPLETED":    3,
		"TASK_STATE_FAILED":       4,
		"TASK_STATE_CANCELED":     5,
		"TASK_STATE_INPUT_NEEDED": 6,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_a2a_a2a_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_proto_a2a_a2a_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_proto_a2a_a2a_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContextId     string                 `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Status        *TaskStatus            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Artifacts     []*Artifact            `protobuf:"bytes,4,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_a2a_a2a_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_a2a_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_a2a_a2a_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *Task) GetStatus() *TaskStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Task) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *Task) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TaskStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         TaskState              `protobuf:"varint,1,opt,name=state,proto3,enum=a2a.TaskState" json:"state,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       *Message               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	mi := &file_proto_a2a_a2a_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_a2a_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_proto_a2a_a2a_proto_rawDescGZIP(), []int{1}
}

func (x *TaskStatus) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *TaskStatus) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TaskStatus) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Parts         []*Part                `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_a2a_a2a_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_a2a_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_a2a_a2a_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type Part struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Data          *structpb.Value        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_proto_a2a_a2a_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_a2a_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_proto_a2a_a2a_proto_rawDescGZIP(), []int{3}
}

func (x *Part) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Part) GetData() *structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Part) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Parts         []*Part                `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_proto_a2a_a2a_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_a2a_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_proto_a2a_a2a_proto_rawDescGZIP(), []int{4}
}

func (x *Artifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *Artifact) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

type PushNotificationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushNotificationConfig) Reset() {
	*x = PushNotificationConfig{}
	mi := &file_proto_a2a_a2a_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushNotificationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNotificationConfig) ProtoMessage() {}

func (x *PushNotificationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_a2a_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNotificationConfig.ProtoReflect.Descriptor instead.
func (*PushNotificationConfig) Descriptor() ([]byte, []int) {
	return file_proto_a2a_a2a_proto_rawDescGZIP(), []int{5}
}

func (x *PushNotificationConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PushNotificationConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TaskStatusUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        *TaskStatus            `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Final         bool                   `protobuf:"varint,3,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusUpdateEvent) Reset() {
	*x = TaskStatusUpdateEvent{}
	mi := &file_proto_a2a_a2a_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusUpdateEvent) ProtoMessage() {}

func (x *TaskStatusUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_a2a_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusUpdateEvent.ProtoReflect.Descriptor instead.
func (*TaskStatusUpdateEvent) Descriptor() ([]byte, []int) {
	return file_proto_a2a_a2a_proto_rawDescGZIP(), []int{6}
}

func (x *TaskStatusUpdateEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusUpdateEvent) GetStatus() *TaskStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TaskStatusUpdateEvent) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type TaskArtifactUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Artifact      *Artifact              `protobuf:"bytes,2,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskArtifactUpdateEvent) Reset() {
	*x = TaskArtifactUpdateEvent{}
	mi := &file_proto_a2a_a2a_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskArtifactUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskArtifactUpdateEvent) ProtoMessage() {}

func (x *TaskArtifactUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_a2a_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskArtifactUpdateEvent.ProtoReflect.Descriptor instead.
func (*TaskArtifactUpdateEvent) Descriptor() ([]byte, []int) {
	return file_proto_a2a_a2a_proto_rawDescGZIP(), []int{7}
}

func (x *TaskArtifactUpdateEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskArtifactUpdateEvent) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

type SendMessageRequest struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Message          *Message                `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	PushNotification *PushNotificationConfig `protobuf:"bytes,2,opt,name=push_notification,json=pushNotification,proto3" json:"push_notification,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_a2a_a2a_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_a2a_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_a2a_a2a_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendMessageRequest) GetPushNotification() *PushNotificationConfig {
	if x != nil {
		return x.PushNotification
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_a2a_a2a_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_a2a_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_a2a_a2a_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_proto_a2a_a2a_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_a2a_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_a2a_a2a_proto_rawDescGZIP(), []int{10}
}

func (x *CancelTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TaskEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TaskEvent_StatusUpdate
	//	*TaskEvent_ArtifactUpdate
	Payload       isTaskEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_proto_a2a_a2a_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_a2a_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_proto_a2a_a2a_proto_rawDescGZIP(), []int{11}
}

func (x *TaskEvent) GetPayload() isTaskEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskEvent) GetStatusUpdate() *TaskStatusUpdateEvent {
	if x != nil {
		if x, ok := x.Payload.(*TaskEvent_StatusUpdate); ok {
			return x.StatusUpdate
		}
	}
	return nil
}

func (x *TaskEvent) GetArtifactUpdate() *TaskArtifactUpdateEvent {
	if x != nil {
		if x, ok := x.Payload.(*TaskEvent_ArtifactUpdate); ok {
			return x.ArtifactUpdate
		}
	}
	return nil
}

type isTaskEvent_Payload interface {
	isTaskEvent_Payload()
}

type TaskEvent_StatusUpdate struct {
	StatusUpdate *TaskStatusUpdateEvent `protobuf:"bytes,1,opt,name=status_update,json=statusUpdate,proto3,oneof"`
}

type TaskEvent_ArtifactUpdate struct {
	ArtifactUpdate *TaskArtifactUpdateEvent `protobuf:"bytes,2,opt,name=artifact_update,json=artifactUpdate,proto3,oneof"`
}

func (*TaskEvent_StatusUpdate) isTaskEvent_Payload() {}

func (*TaskEvent_ArtifactUpdate) isTaskEvent_Payload() {}

var File_proto_a2a_a2a_proto protoreflect.FileDescriptor

const file_proto_a2a_a2a_proto_rawDesc = "" +
	"\n" +
	"\x13proto/a2a/a2a.proto\x12\x03a2a\x1a\x1cgoogle/protobuf/struct.proto\"\xc0\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\x12'\n" +
	"\x06status\x18\x03 \x01(\v2\x0f.a2a.TaskStatusR\x06status\x12+\n" +
	"\tartifacts\x18\x04 \x03(\v2\r.a2a.ArtifactR\tartifacts\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"x\n" +
	"\n" +
	"TaskStatus\x12$\n" +
	"\x05state\x18\x01 \x01(\x0e2\x0e.a2a.TaskStateR\x05state\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12&\n" +
	"\amessage\x18\x03 \x01(\v2\f.a2a.MessageR\amessage\"]\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1f\n" +
	"\x05parts\x18\x02 \x03(\v2\t.a2a.PartR\x05parts\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\"{\n" +
	"\x04Part\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12*\n" +
	"\x04data\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x04data\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"L\n" +
	"\bArtifact\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1f\n" +
	"\x05parts\x18\x02 \x03(\v2\t.a2a.PartR\x05parts\"@\n" +
	"\x16PushNotificationConfig\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"o\n" +
	"\x15TaskStatusUpdateEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12'\n" +
	"\x06status\x18\x02 \x01(\v2\x0f.a2a.TaskStatusR\x06status\x12\x14\n" +
	"\x05final\x18\x03 \x01(\bR\x05final\"]\n" +
	"\x17TaskArtifactUpdateEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12)\n" +
	"\bartifact\x18\x02 \x01(\v2\r.a2a.ArtifactR\bartifact\"\x86\x01\n" +
	"\x12SendMessageRequest\x12&\n" +
	"\amessage\x18\x01 \x01(\v2\f.a2a.MessageR\amessage\x12H\n" +
	"\x11push_notification\x18\x02 \x01(\v2\x1b.a2a.PushNotificationConfigR\x10pushNotification\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11CancelTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa2\x01\n" +
	"\tTaskEvent\x12A\n" +
	"\rstatus_update\x18\x01 \x01(\v2\x1a.a2a.TaskStatusUpdateEventH\x00R\fstatusUpdate\x12G\n" +
	"\x0fartifact_update\x18\x02 \x01(\v2\x1c.a2a.TaskArtifactUpdateEventH\x00R\x0eartifactUpdateB\t\n" +
	"\apayload*\xc0\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TASK_STATE_SUBMITTED\x10\x01\x12\x16\n" +
	"\x12TASK_STATE_WORKING\x10\x02\x12\x18\n" +
	"\x14TASK_STATE_COMPLETED\x10\x03\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x04\x12\x17\n" +
	"\x13TASK_STATE_CANCELED\x10\x05\x12\x1b\n" +
	"\x17TASK_STATE_INPUT_NEEDED\x10\x062\xde\x01\n" +
	"\n" +
	"A2AService\x121\n" +
	"\vSendMessage\x12\x17.a2a.SendMessageRequest\x1a\t.a2a.Task\x12A\n" +
	"\x14SendStreamingMessage\x12\x17.a2a.SendMessageRequest\x1a\x0e.a2a.TaskEvent0\x01\x12)\n" +
	"\aGetTask\x12\x13.a2a.GetTaskRequest\x1a\t.a2a.Task\x12/\n" +
	"\n" +
	"CancelTask\x12\x16.a2a.CancelTaskRequest\x1a\t.a2a.TaskB1Z/github.com/kitporath/project_valhalla/proto/a2ab\x06proto3"

var (
	file_proto_a2a_a2a_proto_rawDescOnce sync.Once
	file_proto_a2a_a2a_proto_rawDescData []byte
)

func file_proto_a2a_a2a_proto_rawDescGZIP() []byte {
	file_proto_a2a_a2a_proto_rawDescOnce.Do(func() {
		file_proto_a2a_a2a_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_a2a_a2a_proto_rawDesc), len(file_proto_a2a_a2a_proto_rawDesc)))
	})
	return file_proto_a2a_a2a_proto_rawDescData
}

var file_proto_a2a_a2a_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_a2a_a2a_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_a2a_a2a_proto_goTypes = []any{
	(TaskState)(0),                  // 0: a2a.TaskState
	(*Task)(nil),                    // 1: a2a.Task
	(*TaskStatus)(nil),              // 2: a2a.TaskStatus
	(*Message)(nil),                 // 3: a2a.Message
	(*Part)(nil),                    // 4: a2a.Part
	(*Artifact)(nil),                // 5: a2a.Artifact
	(*PushNotificationConfig)(nil),  // 6: a2a.PushNotificationConfig
	(*TaskStatusUpdateEvent)(nil),   // 7: a2a.TaskStatusUpdateEvent
	(*TaskArtifactUpdateEvent)(nil), // 8: a2a.TaskArtifactUpdateEvent
	(*SendMessageRequest)(nil),      // 9: a2a.SendMessageRequest
	(*GetTaskRequest)(nil),          // 10: a2a.GetTaskRequest
	(*CancelTaskRequest)(nil),       // 11: a2a.CancelTaskRequest
	(*TaskEvent)(nil),               // 12: a2a.TaskEvent
	(*structpb.Struct)(nil),         // 13: google.protobuf.Struct
	(*structpb.Value)(nil),          // 14: google.protobuf.Value
}
var file_proto_a2a_a2a_proto_depIdxs = []int32{
	2,  // 0: a2a.Task.status:type_name -> a2a.TaskStatus
	5,  // 1: a2a.Task.artifacts:type_name -> a2a.Artifact
	13, // 2: a2a.Task.metadata:type_name -> google.protobuf.Struct
	0,  // 3: a2a.TaskStatus.state:type_name -> a2a.TaskState
	3,  // 4: a2a.TaskStatus.message:type_name -> a2a.Message
	4,  // 5: a2a.Message.parts:type_name -> a2a.Part
	14, // 6: a2a.Part.data:type_name -> google.protobuf.Value
	13, // 7: a2a.Part.metadata:type_name -> google.protobuf.Struct
	4,  // 8: a2a.Artifact.parts:type_name -> a2a.Part
	2,  // 9: a2a.TaskStatusUpdateEvent.status:type_name -> a2a.TaskStatus
	5,  // 10: a2a.TaskArtifactUpdateEvent.artifact:type_name -> a2a.Artifact
	3,  // 11: a2a.SendMessageRequest.message:type_name -> a2a.Message
	6,  // 12: a2a.SendMessageRequest.push_notification:type_name -> a2a.PushNotificationConfig
	7,  // 13: a2a.TaskEvent.status_update:type_name -> a2a.TaskStatusUpdateEvent
	8,  // 14: a2a.TaskEvent.artifact_update:type_name -> a2a.TaskArtifactUpdateEvent
	9,  // 15: a2a.A2AService.SendMessage:input_type -> a2a.SendMessageRequest
	9,  // 16: a2a.A2AService.SendStreamingMessage:input_type -> a2a.SendMessageRequest
	10, // 17: a2a.A2AService.GetTask:input_type -> a2a.GetTaskRequest
	11, // 18: a2a.A2AService.CancelTask:input_type -> a2a.CancelTaskRequest
	1,  // 19: a2a.A2AService.SendMessage:output_type -> a2a.Task
	12, // 20: a2a.A2AService.SendStreamingMessage:output_type -> a2a.TaskEvent
	1,  // 21: a2a.A2AService.GetTask:output_type -> a2a.Task
	1,  // 22: a2a.A2AService.CancelTask:output_type -> a2a.Task
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_a2a_a2a_proto_init() }
func file_proto_a2a_a2a_proto_init() {
	if File_proto_a2a_a2a_proto != nil {
		return
	}
	file_proto_a2a_a2a_proto_msgTypes[11].OneofWrappers = []any{
		(*TaskEvent_StatusUpdate)(nil),
		(*TaskEvent_ArtifactUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_a2a_a2a_proto_rawDesc), len(file_proto_a2a_a2a_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_a2a_a2a_proto_goTypes,
		DependencyIndexes: file_proto_a2a_a2a_proto_depIdxs,
		EnumInfos:         file_proto_a2a_a2a_proto_enumTypes,
		MessageInfos:      file_proto_a2a_a2a_proto_msgTypes,
	}.Build()
	File_proto_a2a_a2a_proto = out.File
	file_proto_a2a_a2a_proto_goTypes = nil
	file_proto_a2a_a2a_proto_depIdxs = nil
}
