apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: valhalla
spec:
  replicas: 1
  selector:
    matchLabels:
      valhalla.io/role: gateway
  template:
    metadata:
      labels:
        valhalla.io/role: gateway
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: gateway
        image: 203.0.113.26:30637/gitea_admin/valhalla-gateway:latest
        args:
        - --agents=chuck=http://chuck.valhalla.svc:8081,ragnar=http://ragnar.valhalla.svc:8081
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: valhalla
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30880
  selector:
    valhalla.io/role: gateway
